// Shared Keeper brand styles for auth emails
export const brand = {
  navy: '#1A2332',
  gold: '#C9A84C',
  cream: '#F5F1EA',
  ink: '#1A2332',
  body: '#4A5568',
  muted: '#8A8F99',
  white: '#ffffff',
  serif: "'Playfair Display', Georgia, 'Times New Roman', serif",
  sans: "'DM Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif",
}

export const styles = {
  main: {
    backgroundColor: brand.white,
    fontFamily: brand.sans,
    margin: 0,
    padding: '32px 0',
  } as const,
  container: {
    backgroundColor: brand.white,
    maxWidth: '560px',
    margin: '0 auto',
    border: `1px solid ${brand.cream}`,
    borderRadius: '12px',
    overflow: 'hidden' as const,
  },
  header: {
    backgroundColor: brand.navy,
    padding: '28px 32px',
    textAlign: 'center' as const,
  },
  monogram: {
    display: 'inline-block',
    width: '44px',
    height: '44px',
    lineHeight: '44px',
    borderRadius: '50%',
    border: `1.5px solid ${brand.gold}`,
    color: brand.white,
    fontFamily: brand.serif,
    fontSize: '22px',
    fontWeight: 'bold' as const,
    textAlign: 'center' as const,
    margin: '0 auto',
  },
  brandName: {
    color: brand.white,
    fontFamily: brand.serif,
    fontSize: '18px',
    letterSpacing: '0.04em',
    margin: '12px 0 0',
  },
  body: {
    padding: '36px 32px 28px',
  },
  h1: {
    fontFamily: brand.serif,
    fontSize: '26px',
    fontWeight: 'normal' as const,
    color: brand.ink,
    margin: '0 0 18px',
    lineHeight: '1.25',
  },
  text: {
    fontFamily: brand.sans,
    fontSize: '15px',
    color: brand.body,
    lineHeight: '1.6',
    margin: '0 0 20px',
  },
  button: {
    backgroundColor: brand.gold,
    color: brand.navy,
    fontFamily: brand.sans,
    fontSize: '15px',
    fontWeight: 'bold' as const,
    borderRadius: '6px',
    padding: '14px 28px',
    textDecoration: 'none',
    display: 'inline-block',
    letterSpacing: '0.02em',
  },
  buttonWrap: {
    textAlign: 'center' as const,
    margin: '8px 0 28px',
  },
  link: {
    color: brand.navy,
    textDecoration: 'underline',
  },
  divider: {
    borderTop: `1px solid ${brand.cream}`,
    margin: '28px 0 20px',
  },
  fineprint: {
    fontFamily: brand.sans,
    fontSize: '13px',
    color: brand.muted,
    lineHeight: '1.5',
    margin: '0 0 8px',
  },
  footer: {
    backgroundColor: brand.cream,
    padding: '20px 32px',
    textAlign: 'center' as const,
  },
  footerText: {
    fontFamily: brand.serif,
    fontSize: '13px',
    color: brand.navy,
    letterSpacing: '0.04em',
    margin: 0,
  },
  code: {
    fontFamily: 'Courier, monospace',
    fontSize: '32px',
    fontWeight: 'bold' as const,
    color: brand.navy,
    backgroundColor: brand.cream,
    padding: '16px 24px',
    borderRadius: '6px',
    letterSpacing: '0.2em',
    textAlign: 'center' as const,
    margin: '0 0 24px',
    display: 'block',
  },
}
